version: '2.2'
  
services:

  ledger:
    image: fetchai/constellation:0.4.1-rc5
    container_name: ledger
    ports:
      - 8000:8000
    restart: on-failure
    command: -standalone -port 8000 -block-interval 3000

  search:
    image: fetchai/oef-search
    volumes:
      - ./node_config.json:/config/node_config.json
    ports:
      - 20000:20000
      - 10000:10000
      - 40000:40000
      - 7500:7500
    command: node no_sh --config_file /config/node_config.json
    restart: on-failure

  api:
    build: api
    volumes:
      - ../agents:/agents
    ports:
      - 8010:8010
    working_dir: /agents/http
    command: go run server.go

  charger_1:
    build: sdk
    container_name: charger_1
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 34 56.21 -9.3 charger1 2b68749f61e3f65d46dd9548556be106d46cc89f0a643eb6b88019e1490263fe 10

  charger_2:
    build: sdk
    container_name: charger_2
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 33 57.1 -10.3 charger2 293d2fc2469343196d8aeb9496cd4626203eaddc111898799fb8402f75c02360 12

  charger_3:
    build: sdk
    container_name: charger_3
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 33 52.55 -9.81 charger3 4f0a08718c81cc92f184403b06f848b9a74608a654e64d624f902d5be77f7c0e 9

  charger_4:
    build: sdk
    container_name: charger_4
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 35 55.05 -8.99 charger4 e01cfb5a6cd69b0cf0b94eca3515f5bb9f2152fa3cf5cb9379599a9bd00de9f7 11

  charger_5:
    build: sdk
    container_name: charger_5
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 36 55.29 -9.35 charger5 e17214080b8ff312dbb5b1a006d36e43e9d81fae6c511ea562ec59f08f9b0aae 10

