version: '2.2'
  
services:

  ledger:
    image: fetchai/constellation:0.4.1-rc5
    container_name: ledger
    ports:
      - 8000:8000
    restart: on-failure
    command: -standalone -port 8000 -block-interval 3000

  search:
    image: fetchai/oef-search
    volumes:
      - ./node_config.json:/config/node_config.json
    ports:
      - 20000:20000
      - 10000:10000
      - 40000:40000
      - 7500:7500
    command: node no_sh --config_file /config/node_config.json
    restart: on-failure

  hello_world:
    build: sdk
    container_name: hello_world
    volumes:
      - ./hello_world:/hello_world
    working_dir: /hello_world
    command: python3 submit_contract.py hello_world.etch

  charger_1:
    build: sdk
    container_name: charger_1
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 34 56.21 -9.3 charger1

  charger_2:
    build: sdk
    container_name: charger_2
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 33 57.1 -10.3 charger2

  charger_3:
    build: sdk
    container_name: charger_3
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 33 52.55 -9.81 charger3

  charger_4:
    build: sdk
    container_name: charger_4
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 35 55.05 -8.99 charger4

  charger_5:
    build: sdk
    container_name: charger_5
    volumes:
      - ../agents:/agents
    working_dir: /agents
    command: python3 charger_agent.py 36 55.29 -9.35 charger5

